### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by PulzHF** [dialtoneuk/Syscrack2017#1]
The game has not released yet

**Comment by PulzHF** [comment]
Oh hey I'm on Discord! MOM GET THE CAMERA

**Comment by dialtoneuk** [comment]
Delayed.

**Comment by DeclanSC4** [comment]
Some information? We wanna know when It will be released.

**Comment by DarkN-exus** [comment]
@dialtoneuk Please, you sound like renato...

**Comment by SilversApprentice** [comment]
@DarkN-exus the difference is that syscrack is actually coming

**Comment by PulzHF** [comment]
Guys, it was a joke.
It's extremely close to release now.

**Comment by DarkN-exus** [comment]
I hope....

**Comment by dialtoneuk** [comment]
The difference is that the entire game can be hosted right now and played around with, a lot more goes into the game regards programming. Most of the time we are spending right now is balancing, creating a playground you can actually play around in, and many more things,

**Comment by golyalpha** [comment]
Hah, sorry about that last one guys. Didn't think that would happen.
